# Generated by Django 5.1.5 on 2025-01-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='gst_certificates/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
