# Generated by Django 5.1.5 on 2025-02-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_seller_first_name_alter_seller_gst_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='gst_certificate',
        ),
    ]
